name: create RESTapi

on:
  push:
    branches: [ main ]
    paths: 
      - '46.intro_to_serverless/**'
    
jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
                python-version: 3.8
          - name: create RESTapi
            run: |
                cd 46.intro_to_serverless
                sam build
          - name: Upload SAM build artifacts
            uses: actions/upload-artifact@v4
            with:
                name: sam-build
                path: 46.intro_to_serverless/.aws-sam/build
            
    deploy:
        needs: build
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
                python-version: 3.8
          - name: Download SAM build artifacts
            uses: actions/download-artifact@v4
            with:
                name: sam-build
                path: 46.intro_to_serverless/.aws-sam/build
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
          - name: deploy RESTapi
            run: |
              cd 46.intro_to_serverless
              sam deploy \
              --stack-name MyStackName \
              --region us-east-1 \
              --capabilities CAPABILITY_IAM \
              --parameter-overrides Param1=Value1 Param2=Value2 \
              --no-confirm-changeset \
              --resolve-s3