name: create RESTapi

on:
  push:
    branches: [ main ]
    paths: 
      - '46.intro_to_serverless/**'
    
jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
              python-version: 3.8
          - name: create RESTapi
            run: |
              cd 46.intro_to_serverless
              sam build
          - name: Upload SAM build artifacts
            uses: actions/upload-artifact@v3
            with:
              name: sam-build
              path: 46.intro_to_serverless/.aws-sam/build
            
    deploy:
        needs: build
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
          - name: Set up Python 3.8
            uses: actions/setup-python@v2
            with:
              python-version: 3.8
          - name: deploy RESTapi
            run: |
              cd 46.intro_to_serverless
              sam deploy --guided